# Generated by Django 5.2.4 on 2025-07-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_todo_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_type',
            new_name='TodoType',
        ),
    ]
